In [1]:
# # Sate Null(H0) and alternative(H1) Hypothesis
# # Choose Level of significance(a)
# # Final Critical Values
# # Find Test Statistic
# # Draw Your Conclusion

# H0 Must always Contain equality (=). H1 always Contains Difference(<>,>,<).

# Z test >30

In [2]:
# Z test >30
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as snsa
import scipy.stats as st

In [3]:
st.norm.ppf(0.95)

np.float64(1.6448536269514722)

In [4]:
s_x = 90
p_u = 82
p_std = 20
n = 81
ap = 0.05

In [5]:
z_cal = (s_x - p_u) / (p_std / np.sqrt(n))
z_cal

np.float64(3.5999999999999996)

In [6]:
z_table = st.norm.ppf(1-ap)
z_table

np.float64(1.6448536269514722)

In [7]:
if z_table < z_cal:
    print("Ha is Right")
else:
    print("Ho is Right")

Ha is Right


In [8]:
# Question 2
import scipy.stats as st
import numpy as np

In [9]:
old_design_data = np.array([72.5, 68.3, 75.8, 70.4, 66.9, 80.2, 74.6, 69.7, 77.3, 71.8,
                   65.4, 73.9, 78.5, 67.2, 76.1, 70.9, 64.8, 79.4, 72.7, 68.9,
                   75.2, 81.3, 69.5, 74.1, 77.8, 66.7, 73.4, 71.2, 78.9, 70.6])

new_design_data = np.array([78.4, 74.6, 81.2, 76.8, 73.5, 84.7, 79.3, 75.1, 82.6, 77.9,
                  71.8, 79.7, 83.4, 72.9, 81.5, 76.4, 70.6, 84.1, 78.8, 74.3,
                  80.9, 85.6, 75.8, 79.5, 82.1, 72.4, 78.2, 77.1, 83.7, 76.5])

In [10]:
mean_new = np.mean(new_design_data)
mean_old = np.mean(old_design_data)

In [11]:
pop_std = 2.5
n_sp = len(new_design_data)
apl = 0.05

In [12]:
z_cal = (mean_new - mean_old) / (pop_std / np.sqrt(n_sp))
z_cal

np.float64(12.079108134847235)

In [13]:
z_table = st.norm.ppf(1 - ap)
z_table

np.float64(1.6448536269514722)

In [14]:
if z_cal > z_table:
    print("ha is right")
else:
    print("h0 is right")

ha is right


T test <30

In [15]:
# Question 2 
import scipy.stats as st
import numpy as np

In [16]:
t_table = st.t.ppf(1 - 0.025, 38)
t_table

np.float64(2.024394163911969)

In [17]:
t_cal = (80 - 75) / (np.sqrt(25 / 20) + (26 / 20))
t_cal

np.float64(2.0677955823875585)

In [18]:
# Question 3
import scipy.stats as st
import numpy as np

In [19]:
t_table = st.t.ppf(1 - 0.025, 19)
t_table

np.float64(2.093024054408263)

In [20]:
before = np.array([50, 60, 45, 65, 55, 70, 40, 75, 80, 65,
70, 60, 50, 55, 45, 75, 60, 50, 65, 70])

after = np.array([60, 70, 55, 75, 65, 80, 50, 85, 90, 70,
75, 65, 55, 60, 50, 80, 65, 55, 70, 75])

In [21]:
std_a = np.std(after)
std_b = np.std(before)
mean_a = np.mean(after)
mean_b = np.mean(before)

In [22]:
t_cal = (mean_a - mean_b) / (np.sqrt(((std_a * std_a) / len(after)) + ((std_b * std_b) / len(before))))
t_cal

np.float64(2.061200527128206)

Chi Square Test

In [23]:
# Question 1
ob = np.array([22,17,20,26,22,13])
ex = np.array([20,20,20,20,20,20])

In [24]:
ob - ex

array([ 2, -3,  0,  6,  2, -7])

In [25]:
np.square(ob - ex)

array([ 4,  9,  0, 36,  4, 49])

In [26]:
np.square(ob - ex) / ex

array([0.2 , 0.45, 0.  , 1.8 , 0.2 , 2.45])

In [27]:
np.sum(np.square(ob - ex) / ex)

np.float64(5.1000000000000005)

In [28]:
# Question 2
import numpy as np

In [29]:
row1 = pd.array([40,45,25,10])
row2 = pd.array([35,30,20,30])

In [30]:
np.sum(row1) + np.sum(row2)

np.int64(235)

In [31]:
# Excepated Value
sum_r1 = np.sum(row1)
sum_r2 = np.sum(row2)
sum_row = np.array([sum_r1,sum_r2])
sum_row

array([120, 115])

In [32]:
sum_cal = (row1 + row2)
sum_cal

<IntegerArray>
[75, 75, 45, 40]
Length: 4, dtype: Int64

In [33]:
exp = []
for i in sum_row:
    for j in sum_cal:
        value = (i * j) / 235 
        exp.append(value)
exp

[np.float64(38.297872340425535),
 np.float64(38.297872340425535),
 np.float64(22.97872340425532),
 np.float64(20.425531914893618),
 np.float64(36.702127659574465),
 np.float64(36.702127659574465),
 np.float64(22.02127659574468),
 np.float64(19.574468085106382)]

In [34]:
# obeservation value
obj = np.array([40,45,25,10,35,30,20,30])
obj

array([40, 45, 25, 10, 35, 30, 20, 30])

In [35]:
len(obj), len(exp)

(8, 8)

In [36]:
# chi square value
squ = (obj - exp)
squ

array([  1.70212766,   6.70212766,   2.0212766 , -10.42553191,
        -1.70212766,  -6.70212766,  -2.0212766 ,  10.42553191])

In [37]:
np.square(squ)

array([  2.89723857,  44.91851517,   4.08555908, 108.69171571,
         2.89723857,  44.91851517,   4.08555908, 108.69171571])

In [38]:
np.square(squ) / exp

array([0.07565012, 1.17287234, 0.17779748, 5.32136525, 0.07893925,
       1.22386679, 0.1855278 , 5.55272895])

In [39]:
np.sum((np.square(obj - exp)) / exp)

np.float64(13.788747987117553)